### ISSUE TITLE
Support for customized worker ID

### ISSUE THREAD

**Issue by polebug** [RSS3-Network/Node#262]
### What feature is it?

In the configuration file, each worker can customize an ID.

### What problem does this feature solve?

In the current design, the worker's id is determined by the parameters field. ⬇️

```
    parameters:
      block_number_start:
      block_number_target:
      rpc_thread_blocks:
```

When a parameter is changed, a new worker will be generated, and it will index the data from the start, which is a huge waste of time.

### This is not a duplicated feature request or new worker proposal

- [X] I have searched [existing issues](https://github.com/rss3-network/node/issues) to ensure this feature has not already been requested and this is not a [New Worker](https://github.com/rss3-network/node/issues/new?assignees=&labels=worker&projects=&template=worker_coverage.yml).
